export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_SUCCESS ="GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL ="GET_ITEMS_FAIL";

export const ADD_ITEMS_START = "ADD_ITEMS_START";
export const ADD_ITEMS_SUCCESS ="ADD_ITEMS_SUCCESS"
export const ADD_ITEMS_FAILURE ="ADD_ITEMS_FAILURE"
export const ADD_TO_CART = "ADD_TO_CART"

export const DELETE_ITEM_START = "DELETE_ITEM_START";
export const DELETE_ITEM_SUCCESS = "DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAILURE ="DELETE_ITEM_FAILURE"

export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const CHECKOUT_REQUEST ="CHECKOUT_REQUEST"

